import type { Space, Post, User, Notification } from '@/types'

export const MOCK_USER: User = {
  uid: 'u1',
  email: 'ayse.kaya@ogr.gelisim.edu.tr',
  studentEmail: 'ayse.kaya@ogr.gelisim.edu.tr',
  displayName: 'Ayşe Kaya',
  department: 'Bilgisayar Mühendisliği',
  grade: 3,
  role: 'student',
  isVerified: true,
  joinedAt: new Date('2024-09-01'),
  lastActiveAt: new Date(),
}

export const MOCK_SPACES: Space[] = [
  {
    id: 's1',
    name: 'Bilgisayar Mühendisliği',
    slug: 'bilgisayar-muhendisligi',
    description: 'Bilgisayar Mühendisliği bölümü öğrencileri için genel alan',
    iconEmoji: '💻',
    department: 'Bilgisayar Mühendisliği',
    isPublic: true,
    memberCount: 342,
    createdBy: 'admin',
    createdAt: new Date('2024-09-01'),
    channels: [
      {
        id: 'c1', spaceId: 's1', name: 'duyurular', slug: 'duyurular',
        description: 'Bölüm duyuruları', type: 'announcement', icon: '📣',
        color: 'amber', rules: [], postCount: 45, isReadOnly: true, isPinned: true,
        createdAt: new Date(),
      },
      {
        id: 'c2', spaceId: 's1', name: 'akademik-destek', slug: 'akademik-destek',
        description: 'Soru ve cevaplar', type: 'academic', icon: '📚',
        color: 'green', rules: [], postCount: 128, isReadOnly: false, isPinned: false,
        createdAt: new Date(),
      },
      {
        id: 'c3', spaceId: 's1', name: 'kaynak-arsivi', slug: 'kaynak-arsivi',
        description: 'PDF ve notlar', type: 'archive', icon: '🗂️',
        color: 'purple', rules: [], postCount: 89, isReadOnly: false, isPinned: false,
        createdAt: new Date(),
      },
      {
        id: 'c4', spaceId: 's1', name: 'ilan-panosu', slug: 'ilan-panosu',
        description: 'Özel ders ilanları', type: 'listing', icon: '📌',
        color: 'red', rules: [], postCount: 23, isReadOnly: false, isPinned: false,
        createdAt: new Date(),
      },
      {
        id: 'c5', spaceId: 's1', name: 'oneri-kutusu', slug: 'oneri-kutusu',
        description: 'Öneri ve istekler', type: 'suggestion', icon: '💡',
        color: 'teal', rules: [], postCount: 15, isReadOnly: false, isPinned: false,
        createdAt: new Date(),
      },
      {
        id: 'c6', spaceId: 's1', name: 'sosyal-alan', slug: 'sosyal-alan',
        description: 'Tanışma ve etkinlikler', type: 'social', icon: '🎉',
        color: 'blue', rules: [], postCount: 67, isReadOnly: false, isPinned: false,
        createdAt: new Date(),
      },
    ],
  },
  {
    id: 's2',
    name: 'Elektrik-Elektronik',
    slug: 'elektrik-elektronik',
    description: 'EEM bölümü öğrencileri için alan',
    iconEmoji: '⚡',
    department: 'Elektrik-Elektronik Mühendisliği',
    isPublic: true,
    memberCount: 218,
    createdBy: 'admin',
    createdAt: new Date('2024-09-01'),
    channels: [],
  },
  {
    id: 's3',
    name: 'Genel Kampüs',
    slug: 'genel-kampus',
    description: 'Tüm IGÜ öğrencileri için ortak alan',
    iconEmoji: '🏛️',
    isPublic: true,
    memberCount: 1204,
    createdBy: 'admin',
    createdAt: new Date('2024-09-01'),
    channels: [],
  },
]

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    channelId: 'c1',
    spaceId: 's1',
    authorId: 'mod1',
    author: { uid: 'mod1', displayName: 'Dr. Mehmet Yılmaz', role: 'moderator' },
    title: 'Veri Yapıları Final Sınavı — Yer Değişikliği',
    content: 'Veri Yapıları ve Algoritmalar dersi final sınavı **A-101 yerine B-201\'de** yapılacaktır. Öğrencilerin bunu not alması önemle rica olunur. Sınav saatinde herhangi bir değişiklik yoktur.',
    attachments: [],
    tags: ['sınav', 'veri-yapıları'],
    isPinned: true,
    isAnnouncement: true,
    status: 'published',
    commentCount: 0,
    viewCount: 156,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'p2',
    channelId: 'c2',
    spaceId: 's1',
    authorId: 'u2',
    author: { uid: 'u2', displayName: 'Emre Demir', role: 'student' },
    title: 'Dinamik Programlama — Fibonacci ile başlangıç?',
    content: 'Algoritmalar dersinde DP konusuna geçtik ama tam anlayamadım. Fibonacci\'yi memoization ile çözdüğümüzde zaman karmaşıklığı neden O(n)\'e düşüyor? Bunu anlayamadım.',
    attachments: [],
    tags: ['algoritma', 'dp'],
    isPinned: false,
    isAnnouncement: false,
    status: 'published',
    commentCount: 7,
    viewCount: 43,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'p3',
    channelId: 'c3',
    spaceId: 's1',
    authorId: 'u3',
    author: { uid: 'u3', displayName: 'Zeynep Arslan', role: 'student' },
    title: 'Veri Tabanı Sistemleri — Geçmiş Yıl Soruları',
    content: '2021-2024 yılları arasındaki tüm vize ve final sorularını derledim. İyi çalışmalar!',
    attachments: [
      {
        id: 'a1', postId: 'p3', name: 'VT_Gecmis_Sorular_2021-2024.pdf',
        url: '#', type: 'pdf', size: 4200000,
        uploadedBy: 'u3', uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
      },
    ],
    tags: ['vize', 'final', 'veri-tabanı'],
    isPinned: false,
    isAnnouncement: false,
    status: 'published',
    commentCount: 12,
    viewCount: 234,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    type: 'announcement',
    title: 'Yeni Duyuru',
    body: 'Veri Yapıları sınavında yer değişikliği oldu',
    link: '/dashboard/spaces/bilgisayar-muhendisligi/duyurular/p1',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'n2',
    userId: 'u1',
    type: 'new_comment',
    title: 'Yorumunuza yanıt geldi',
    body: 'Emre Demir sorunuza yanıt verdi',
    link: '/dashboard/spaces/bilgisayar-muhendisligi/akademik-destek/p2',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: 'n3',
    userId: 'u1',
    type: 'new_post',
    title: 'Yeni kaynak paylaşıldı',
    body: 'Zeynep Arslan geçmiş yıl soruları yükledi',
    link: '/dashboard/spaces/bilgisayar-muhendisligi/kaynak-arsivi/p3',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
]
